[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "echo 'Dependencies will be installed during build phase'"
]

[phases.build]
cmds = [
    "chmod +x build.sh",
    "./build.sh"
]

[start]
cmd = "node server-supabase.js" 